#!/usr/bin/env bash
# Generate a local Compose environment file for an isolated dev instance.

set -euo pipefail

INSTANCE_NAME="${1:-URF010}"
ENV_FILE="${2:-.env.dev}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

if ! [[ "${INSTANCE_NAME}" =~ ^URF[0-9]{3}$ ]]; then
  echo "Invalid instance name: ${INSTANCE_NAME}" >&2
  echo "Expected format: URF000 through URF999" >&2
  exit 1
fi

PROJECT_NAME="$(echo "urfd-${INSTANCE_NAME}" | tr '[:upper:]' '[:lower:]')"
DEV_DATA_DIR="./data/dev/${INSTANCE_NAME}"
INSTANCE_NUM=$((10#${INSTANCE_NAME:3}))
PORT_OFFSET=$((INSTANCE_NUM * 100))

MAX_SAFE_INSTANCE=35
if (( INSTANCE_NUM > MAX_SAFE_INSTANCE )); then
  echo "Instance ${INSTANCE_NAME} would assign ports above 65535 with the current offset scheme." >&2
  echo "Use URF000 through URF035, or change deployment/scripts/calculate-ports.sh." >&2
  exit 1
fi

mkdir -p "${PROJECT_ROOT}/config/local"
cp -n "${PROJECT_ROOT}"/config/defaults/*.ini "${PROJECT_ROOT}/config/local/" 2>/dev/null || true

mkdir -p \
  "${PROJECT_ROOT}/data/dev/${INSTANCE_NAME}/logs" \
  "${PROJECT_ROOT}/data/dev/${INSTANCE_NAME}/audio" \
  "${PROJECT_ROOT}/data/dev/${INSTANCE_NAME}/dashboard"

{
  echo "# Generated by scripts/dev-env.sh. Do not commit."
  echo "INSTANCE_NAME=${INSTANCE_NAME}"
  echo "COMPOSE_PROJECT_NAME=${PROJECT_NAME}"
  echo "IMAGE_VERSION=latest"
  echo "CONFIG_DIR=./config/local"
  echo "DASHBOARD_CONFIG_DIR=./config/dashboard"
  echo "LOG_DIR=${DEV_DATA_DIR}/logs"
  echo "AUDIO_DIR=${DEV_DATA_DIR}/audio"
  echo "DASHBOARD_DATA_DIR=${DEV_DATA_DIR}/dashboard"
  echo "PORT_AMI=$((5038 + PORT_OFFSET))"
  "${PROJECT_ROOT}/deployment/scripts/calculate-ports.sh" "${INSTANCE_NAME}" | grep '^PORT_'
} > "${PROJECT_ROOT}/${ENV_FILE}"

echo "Wrote ${ENV_FILE} for ${INSTANCE_NAME} (${PROJECT_NAME})"
