# TCD Configuration File for URF239
# Format: Key=Value

# Connection to URFD (or Transcoder Server)
ServerAddress=127.0.0.1
Port=10101

# Modules to support (must match URFD config)
Modules=ADMSZ

# Audio Gains (dB)
DStarGainIn=0
DStarGainOut=0
DmrYsfGainIn=0
DmrYsfGainOut=0

# USRP Gains
UsrpTxGain=0
UsrpRxGain=0

# AGC Settings
AGC=true
AGCTargetLevel=-18.0
